---
apiVersion: v1
kind: Namespace
metadata:
  name: elevate-sec
spec: {}
status: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elevate-sec
  namespace: elevate-sec
data:
  config-development.json: |
    {
    "port": 9000,
    "connection_string": "https://incident-api.use1stag.elevatesecurity.io",
    "timeout": 10
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elevate-sec
  namespace: elevate-sec
  labels:
    app: elevate-sec
    type: api
spec:
  selector:
    matchLabels:
      app: elevate-sec
  revisionHistoryLimit: 10
  replicas: 1
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: elevate-sec
        type: api
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: elevate-sec
            items:
              - key: config-development.json
                path: config-development.json
        - name: secrets
          secret:
            secretName: elevate-sec
            items:
              - key: auth_username
                path: auth_username
              - key: auth_password
                path: auth_password
      containers:
        - name: main
          # with Helm chart and ArgoCD this will be a pinned tag
          image: "magzim21/elevate-sec:latest"
          # Helm chart: only for "latest" image tag
          imagePullPolicy: Always
          args:
            - "--config /app/config/config-development.json"
            - "--secrets-path /app/config/secrets"
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: secrets
              mountPath: /app/config/secrets
          resources:
            requests:
              memory: 200Mi
              cpu: "0.2"
            limits:
              memory: 200Mi
              cpu: "0.2"
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            # periodSeconds: 3600
            timeoutSeconds: 10
            httpGet:
              path: /incidents
              port: 9000
              scheme: HTTP
          startupProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 10
            httpGet:
              # host: ""
              path: /incidents
              port: 9000
              scheme: HTTP
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - elevate-sec
                topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: elevate-sec
  namespace: elevate-sec
  labels:
    app: elevate-sec
spec:
  ports:
    - port: 80
      targetPort: 9000
  type: ClusterIP
  selector:
    app: elevate-sec
